import avatar from 'src/shared/icons/userAvatar.png';

const userCardsData = [
  {
    id: '1',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Екатерина',
    surname: 'Константинопольская',
    secondname: 'Олеговна',
    position: 'Продакт-менеджер для специалистов с опытом',
    date: '2024-02-19T13:45:00',
    statusActive: true,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
    trackingNumber: 'RV 12345678',
    userStatus: 'Active',
  },
  {
    id: '2',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Марина',
    surname: 'Князева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: true,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
    trackingNumber: 'RV 12345678',
    userStatus: 'OnPause',
  },
  {
    id: '3',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: true,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
    trackingNumber: 'RV 12345678',
    userStatus: 'PendingConfirmation',
  },
  {
    id: '4',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: true,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
    trackingNumber: 'RV 12345678',
    userStatus: 'Inactive',
  },
  {
    id: '5',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: false,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
    trackingNumber: 'RV 12345678',
    userStatus: 'Active',
  },
  {
    id: '6',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: false,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
    trackingNumber: 'RV 12345678',
    userStatus: 'Active',
  },
  {
    id: '7',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Варвара',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: false,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
    trackingNumber: 'RV 12345678',
    userStatus: 'PendingConfirmation',
  },
];

export { userCardsData };
