import avatar from 'src/shared/icons/userAvatar.png';

const userCardsData = [
  {
    id: '1',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: true,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
  },
  {
    id: '2',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: true,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
  },
  {
    id: '3',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: true,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
  },
  {
    id: '4',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: true,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
  },
  {
    id: '5',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: false,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
  },
  {
    id: '6',
    avatar: avatar,
    telegram: 'ponomarevaangelina',
    name: 'Ангелина',
    surname: 'Пономарева',
    secondname: 'Сергеевна',
    position: 'Продвинутый Go-разработчик',
    date: '2024-02-19T13:45:00',
    statusActive: false,
    promocode: 'Выдра',
    activationDate: '2024-01-31T13:45:00',
  },
];

export { userCardsData };
