version: '3.3'

services:
  db:
    image: postgres:16.1-alpine3.19
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  backend:
    image: aleksey2299/ambassadors_backend:latest
    entrypoint: /app/backend_entrypoint.sh
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: natashasolntseva/ambassadors_frontend:latest
    command: cp -r /app/dist/. /frontend_static/
    volumes:
      - static:/frontend_static

  redis:
    image: redis:7.2.4-alpine
    expose:
      - 6379

  worker:
    image: aleksey2299/ambassadors_backend:latest
    command: celery -A ambassadors_project worker -B -l info
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - backend
      - redis

  nginx:
    image: aleksey2299/ambassadors_nginx:latest
    env_file: .env
    ports:
      - 8000:80
      - 443:443
    volumes:
      - static:/static/
      - media:/media/
      - certs:/etc/letsencrypt

volumes:
  postgres_data:
  static:
  media:
  certs:
